/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=ClaudexBindings` (hash: 73e733569aa2401465876772cd78d915)
interface __BaseEnv_ClaudexBindings {
	AUTH_BUCKET: R2Bucket;
	CODEX_AUTH_OBJECT: "codex-primary.json";
	CLAUDEX_PROXY_CONTAINER: DurableObjectNamespace<import("./src/index").ClaudexProxyContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ClaudexProxyContainer";
	}
	interface Env extends __BaseEnv_ClaudexBindings {}
}
interface ClaudexBindings extends __BaseEnv_ClaudexBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CODEX_AUTH_OBJECT">> {}
}
